### ISSUE TITLE
Design of Octocat?

### ISSUE THREAD

**Issue by ZaneEme** [BenjaminMichaelis/BenjaminMichaelis#4]
I was wondering where you got that design for the Octocat logo? Is it something you designed yourself or is there a builder website I'm missing?
Thanks

**Comment by BenjaminMichaelis** [comment]
Here's two sites to help that I used to design my own. They do have some bugs that make export difficult sometimes but hopefully this helps!
https://myoctocat.dev/
https://myoctocat.com/build-your-octocat/
